const defaultProjects = [
    {
        id: 1,
        title: 'E-Ticaret Backend API',
        titleEn: 'E-Commerce Backend API',
        description: 'ASP.NET Core Web API ile geliştirilmiş, JWT tabanlı güvenli e-ticaret backend sistemi. Kullanıcı yönetimi, ürün CRUD işlemleri ve rol bazlı yetkilendirme.',
        descriptionEn: 'Secure e-commerce backend system developed with ASP.NET Core Web API and JWT authentication. User management, product CRUD operations and role-based authorization.',
        category: 'web',
        status: 'Yayında',
        featured: true,
        tags: ['ASP.NET Core', 'C#', 'JWT', 'Entity Framework', 'REST API', 'Swagger'],
        image: '/images/projects/ecommerce-api.jpg',
        github: 'https://github.com/OmerUzunsoy/E-Ticaret-Backend-JWT-Auth-',
        download: '#',
        lastUpdate: '2024-11-29'
    },
    {
        id: 2,
        title: 'Film Arşivi API',
        titleEn: 'Movie Archive API',
        description: 'ASP.NET Core ve Entity Framework Core ile geliştirilmiş film veritabanı API\'si. SQL Server üzerinde CRUD operasyonları.',
        descriptionEn: 'Movie database API developed with ASP.NET Core and Entity Framework Core. CRUD operations on SQL Server with Docker support.',
        category: 'web',
        status: 'Yayında',
        featured: true,
        tags: ['ASP.NET Core', 'C#', 'Entity Framework', 'SQL Server', 'Docker', 'REST API'],
        image: '/images/projects/film-arsivi.jpg',
        github: 'https://github.com/OmerUzunsoy/FilmArsivi-API',
        download: '#',
        lastUpdate: '2024-11-28'
    },
    {
        id: 3,
        title: 'Kütüphane Yöneticisi',
        titleEn: 'Library Manager',
        description: 'C# ve ADO.NET ile geliştirilmiş konsol tabanlı kütüphane yönetim uygulaması. SQL Server veritabanı entegrasyonu ve SQL Injection koruması.',
        descriptionEn: 'Console-based library management application developed with C# and ADO.NET. SQL Server database integration with SQL Injection protection.',
        category: 'desktop',
        status: 'Yayında',
        featured: false,
        tags: ['C#', '.NET', 'ADO.NET', 'SQL Server', 'Console App'],
        image: '/images/projects/library-manager.jpg',
        github: 'https://github.com/OmerUzunsoy/LibraryManager',
        download: '#',
        lastUpdate: '2024-11-27'
    },
    {
        id: 4,
        title: 'NoteTaker - Not Defteri',
        titleEn: 'NoteTaker - Personal Notes',
        description: 'C# ile geliştirilmiş, dosya sistemi üzerinde çalışan kişisel not defteri uygulaması. System.IO ile dosya okuma/yazma işlemleri.',
        descriptionEn: 'Personal note-taking application built with C# using file system operations. File read/write operations with System.IO library.',
        category: 'desktop',
        status: 'Yayında',
        featured: false,
        tags: ['C#', '.NET', 'System.IO', 'Console App', 'File Operations'],
        image: '/images/projects/note-taker.jpg',
        github: 'https://github.com/OmerUzunsoy/NoteTaker',
        download: '#',
        lastUpdate: '2024-11-26'
    },
    {
        id: 5,
        title: 'Console Bank',
        titleEn: 'Console Bank',
        description: 'C# ile geliştirilmiş konsol tabanlı bankacılık simülasyonu. Şifre korumalı giriş, bakiye sorgulama, para yatırma/çekme işlemleri.',
        descriptionEn: 'Console-based banking simulation developed with C#. Password-protected login, balance inquiry, deposit and withdrawal operations.',
        category: 'desktop',
        status: 'Yayında',
        featured: false,
        tags: ['C#', '.NET 9', 'Console App', 'Banking', 'Simulation'],
        image: '/images/projects/console-bank.jpg',
        github: 'https://github.com/OmerUzunsoy/ConsoleBank',
        download: '#',
        lastUpdate: '2024-11-25'
    },
    {
        id: 6,
        title: 'UzunsClicker V2',
        titleEn: 'UzunsClicker V2',
        description: 'Modern ve güçlü mouse otomatik tıklama uygulaması. 1-10.000 CPS, Dark/Light tema, TR/EN dil desteği, gelişmiş kısayol sistemi.',
        descriptionEn: 'Modern and powerful mouse auto-clicker application. 1-10,000 CPS, Dark/Light theme, TR/EN language support, advanced hotkey system.',
        category: 'desktop',
        status: 'Yayında',
        featured: true,
        tags: ['C#', 'WPF', '.NET Framework', 'Windows API', 'MVVM', 'Desktop App'],
        image: '/images/projects/uzuns-clicker.jpg',
        github: 'https://github.com/OmerUzunsoy/UzunsClicker-V2',
        download: 'https://github.com/OmerUzunsoy/UzunsClicker-V2/releases/latest',
        lastUpdate: '2024-08-10'
    }
];

export default defaultProjects;
